author: IndexDev
name: UtilsLib

version: 1.1.0
api: 5.0.0

main: IndexDev\UtilsLib\Main

commands:
  utils:
    description: Utilidades generales
    permission: utilslib.command
permissions:
  utilslib.command:
    default: op
